"""initial

Revision ID: 7e0a00d19520
Revises: 
Create Date: 2026-07-06 09:23:43.438476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e0a00d19520'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('titulo', sa.String(length=512), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=256), nullable=True),
    sa.Column('imagem', sa.String(length=2048), nullable=True),
    sa.Column('texto_alternativo', sa.String(length=512), nullable=True),
    sa.Column('source_file', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'PUBLISHED', 'FAILED', name='newsstatus'), nullable=False),
    sa.Column('reviewed_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('news_id', sa.String(length=36), nullable=False),
    sa.Column('portal_url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'IN_PROGRESS', 'SUCCESS', 'FAILED', name='publicationstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_news_id'), 'publications', ['news_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_news_id'), table_name='publications')
    op.drop_table('publications')
    op.drop_table('news')
    # ### end Alembic commands ###
